version: '3.6'

services:
    api:
        container_name: mullberry-backend
        image: mullberry-backend
        ports:
            - 8000:8080
        volumes:
            - ./:/app
        build:
          dockerfile: ./app/Dockerfile